# Generated by Django 4.1.7 on 2023-04-23 08:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('konu', models.CharField(blank=True, max_length=50)),
                ('mesaj', models.TextField(blank=True, max_length=300)),
                ('durum', models.CharField(choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Closed', 'Kapandı')], default='Yeni', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('not_ekle', models.CharField(blank=True, max_length=100)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SayfaAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('firma', models.CharField(max_length=200)),
                ('adres', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('hakkimizda', ckeditor_uploader.fields.RichTextUploadingField()),
                ('iletisim', ckeditor_uploader.fields.RichTextUploadingField()),
                ('referanslar', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
