# Generated by Django 4.1.7 on 2023-04-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sayfaayarlari',
            old_name='aciklama',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sayfaayarlari',
            old_name='baslik',
            new_name='title',
        ),
    ]
