# Generated by Django 4.1.7 on 2023-04-18 15:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_aciklama_sayfaayarlari_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('konu', models.CharField(blank=True, max_length=50)),
                ('mesaj', models.TextField(blank=True, max_length=300)),
                ('durum', models.CharField(choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Closed', 'Kapandı')], default='Yeni', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('not_ekle', models.CharField(blank=True, max_length=100)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sayfaayarlari',
            name='hakkimizda',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='sayfaayarlari',
            name='iletisim',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='sayfaayarlari',
            name='referanslar',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
