# Generated by Django 4.1.7 on 2023-04-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_iletisimmesaji_alter_sayfaayarlari_hakkimizda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iletisimmesaji',
            old_name='mesaj',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='iletisimmesaji',
            old_name='ad',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iletisimmesaji',
            old_name='konu',
            new_name='subject',
        ),
    ]
