# Generated by Django 4.1.7 on 2023-05-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_kullanciprofili'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KullanciProfili',
        ),
    ]
