# Generated by Django 4.1.7 on 2023-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_name_iletisimmesaji_ad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iletisimmesaji',
            old_name='ad',
            new_name='adsoyad',
        ),
    ]
