# Generated by Django 4.1.7 on 2023-05-23 08:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_kullanciprofili'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=200)),
                ('cevap', ckeditor_uploader.fields.RichTextUploadingField()),
                ('durum', models.CharField(choices=[('True', 'Yayınla'), ('False', 'Yayınlama')], max_length=10)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
                ('ordernumber', models.IntegerField()),
            ],
        ),
    ]
