# Generated by Django 4.1.7 on 2023-04-23 08:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='translated_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Karton Kapak', 'Karton Kapak'), ('Kuşe Kapak', 'Kuşe Kapak')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(blank=True, max_length=50)),
                ('yorum', models.CharField(blank=True, max_length=300)),
                ('yorum_puani', models.IntegerField(default=1)),
                ('durum', models.CharField(choices=[('New', 'Yeni'), ('False', 'False'), ('True', 'True')], default='Yeni', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rght', models.IntegerField(blank=True, null=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category'),
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
