# Generated by Django 4.1.7 on 2023-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_availability_books_translated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorumlar',
            name='durum',
            field=models.CharField(choices=[('New', 'Yeni'), ('False', 'Onaylanmadı'), ('True', 'Onaylandı')], default='Yeni', max_length=10),
        ),
    ]
