# Generated by Django 4.1.7 on 2023-04-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_category_books_bookcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100)),
                ('resim', models.ImageField(blank=True, upload_to='images/')),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
            ],
        ),
    ]
