# Generated by Django 4.1.7 on 2023-04-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_resimler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='detail',
            field=models.TextField(max_length=1500),
        ),
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(blank=True, max_length=50)),
                ('yorum', models.CharField(blank=True, max_length=300)),
                ('yorum_puani', models.IntegerField(default=1)),
                ('durum', models.CharField(choices=[('New', 'Yeni'), ('False', 'False'), ('True', 'True')], default='Yeni', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
