# Generated by Django 4.1.7 on 2023-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_books_sliderbooks_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='sliderbooks',
            new_name='sliderimage',
        ),
    ]
