# Generated by Django 4.1.7 on 2023-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_sliderbooks_books_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='sliderimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
