# Generated by Django 4.1.7 on 2023-04-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resimler',
            old_name='resim',
            new_name='image',
        ),
    ]
