# Generated by Django 4.1.7 on 2023-04-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_resim_resimler_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resimler',
            old_name='books_id',
            new_name='books',
        ),
    ]
