# Generated by Django 4.1.7 on 2023-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_books_id_resimler_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resimler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
