# Generated by Django 4.1.7 on 2023-04-18 15:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_resimler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
