# Generated by Django 4.1.7 on 2023-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_books_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='lft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='rght',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
