# Generated by Django 4.1.7 on 2023-04-22 14:03

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_bookcategory_level_bookcategory_tree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.bookcategory'),
        ),
    ]
