# Generated by Django 4.1.7 on 2023-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookcategory_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='bookcategory',
            new_name='category',
        ),
    ]
