# Generated by Django 4.1.7 on 2023-05-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alisverissepeti_bookname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alisverissepeti',
            name='bookname',
        ),
    ]
