# Generated by Django 4.1.7 on 2023-05-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_alisverissepeti_bookname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparis',
            old_name='code',
            new_name='siparis_kodu',
        ),
    ]
