# Generated by Django 4.1.7 on 2023-05-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_yorumlar_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_rename_code_siparis_siparis_kodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriSepeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.books')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
